apiVersion: apps/v1
kind: Deployment
metadata:
  name:  oauth2-server
  namespace: zt
  labels:
    app: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v1
      apply: oauth2-server
  template:
    metadata:
      labels:
        app: v1
        apply: oauth2-server
    spec:
      containers:
      - name: oauth2-server
        image: harbor.domain.com/zt/oauth2-server:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
  namespace: zt
  labels:
    apply: oauth2-server
    app: v1
spec:
  selector:
    apply: oauth2-server
    app: v1
  type: NodePort
  ports:
   - port: 8080
     targetPort: 8080